#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "gitea-runner"
name = "Gitea Runner"
description.en = "Runner for Gitea based on act"
description.fr = "Runner pour Gitea basé sur act"

version = "0.2.6~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
code = "https://gitea.com/gitea/act_runner"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.token]
    ask.en = "This token can be retrieved at this location: http://192.168.8.8:3000/admin/actions/runners"
    ask.fr = "Ce token peut être récupéré à cet emplacement : http://192.168.8.8:3000/admin/actions/runners"
    type = "string"
    example = "xxxx"

    [install.gitea_url]
    ask.en = "Please enter Gitea URL"
    ask.fr = "Veuillez entrer l'URL de Gitea"
    type = "string"
    example = "https://gitea.com/"

[resources]

    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://gitea.com/gitea/act_runner/releases/download/v0.2.6/act_runner-0.2.6-linux-amd64"
        amd64.sha256 = "234c2bdb871e7b0bfb84697f353395bfc7819faf9f0c0443845868b64a041057"
        arm64.url = "https://gitea.com/gitea/act_runner/releases/download/v0.2.6/act_runner-0.2.6-linux-arm64"
        arm64.sha256 = "f5c477b54d7db5289acee6b59cd96b28de4bdda809f79e830662d4c952b2914d"
        armhf.url = "https://gitea.com/gitea/act_runner/releases/download/v0.2.6/act_runner-0.2.6-linux-arm-7"
        armhf.sha256 = "b9e7d4058e335513be0a76180e11f4f3971486ad7d64358f7ecde734b8ca19fa"
        in_subdir = false
        extract = false
        rename = "act_runner"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
