#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.private", "install.multi"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.token = "GR1348941_Rew7obt4p9jZyQUtHLx"
    args.gitea_url = "https://gitea.com/"
